delay_seconds = 1
ignore_seconds = 1
score_cutoff = 0.30
everything_walk = true
everything_instance = "1.5a"
everything_retry_seconds = 60
classified_tag_model = 'e621-model-{0}'
classified_tag_score = 'e621-score-{0}'
include_folders = [
	"D:\\Shared\\Archived\\Media\\Images\\Yiffy\\Furry\\Glyn\\TagTest",
	# "C:\\Users\\falkn\\Downloads\\yiffy\\Folder 1",
	# "C:\\Users\\falkn\\Downloads\\yiffy\\Folder 2",
	# "D:\\Downloads\\yiffy\\Folder 1",
	# "D:\\Downloads\\yiffy\\Folder 2",
	# "/Users/falkner/Downloads/yiffy",
]

# Patterns follow the Python pattern language:
# https://docs.python.org/3/library/pathlib.html#pathlib-pattern-language
include_patterns = [
	# Don't include GIFs or BMPs because they do not accept tags.
	'*.jpg',
	'*.jpeg',
	'*.jfif',
	'*.png',
	'*.webp'
]

exclude_patterns = [
	"D:\\Shared\\Archived\\Media\\Images\\Yiffy\\Furry\\Glyn\\TagTest\\Ignore\\*",
	"D:\\Shared\\Archived\\Media\\Images\\Yiffy\\Furry\\Glyn\\TagTest\\Ignore\\**\\*",
	# "C:\\Users\\falkn\\Downloads\\yiffy\\Folder 1\\Ignore\\*",
	# "C:\\Users\\falkn\\Downloads\\yiffy\\Folder 1\\Ignore\\**\\*",
	# "D:\\Downloads\\yiffy\\Folder 1\\Ignore\\*",
	# "D:\\Downloads\\yiffy\\Folder 1\\Ignore\\**\\*",
	# "/Users/falkner/Downloads/yiffy/ignore/**/*",
	# "/Users/falkner/Downloads/yiffy/ignore/*",
]

[logging]
level = "info"
file_size = 10485760
max_files = 10
