delay_seconds = 1
score_cutoff = 0.30
classified_tag = 'e621-jtp3'
include_folders = [
	"D:\\Shared\\Archived\\Media\\Images\\Yiffy\\Furry\\Glyn\\TagTest",
	# "D:\\Downloads\\yiffy\\Folder 1",
	# "D:\\Downloads\\yiffy\\Folder 2",
	# "/Users/falkner/Downloads/yiffy",
]

# Patterns follow the Python pattern language:
# https://docs.python.org/3/library/pathlib.html#pathlib-pattern-language
include_patterns = [
	# Don't include GIFs because they do not accept tags.
	'*.jpg',
	'*.jpeg',
	'*.png',
	'*.bmp',
	'*.webp'
]

exclude_patterns = [
	# "D:\\Downloads\\yiffy\\Folder 1\\Ignore\\**\\*",
]