delay = 1
image_extensions = ['.jpg', '.jpeg', '.png', '.bmp', '.webp'] # Exclude GIF because it does not accept tags.
score_cutoff = 0.30
classified_tag = 'e621-jtp3'
watch_root = "D:/Shared/Archived/Media/Images/Yiffy/Furry/Glyn/TagTest"
# watch_root = "D:/Downloads/yiffy"
# watch_root = "/Users/falkner/Downloads/yiffy"
